name: Docker Build and Push

# DOCKER_USERNAME
# DOCKER_PASSWORD

on:
  push:
    tags:
      - '*'  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.kexie.space
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the Git tag
        id: git_tag
        run: |
          git_tag=$(git describe --tags --exact-match 2>/dev/null || echo "none")
          echo "::set-output name=tag::$git_tag"

      - name: Build and Push Docker image
        run: |
            docker buildx build --platform linux/amd64 \
              -f ./deploy/Dockerfile \ 
              -t docker.kexie.space/kexie/kexie-hello-web:${{ steps.git_tag.outputs.tag }} \
              -t docker.kexie.space/kexie/kexie-hello-web:latest \
              --push .
       

